name: first workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline
        run: |-
          node -v
          npm -v

  parrell:
    runs-on: ubuntu-latest
    needs: [run-shell-commands]
    steps:
      - name: second jobs
        run: echo "second job"
      - name : second two
        run: echo "scond two"

  third:
      runs-on: ubuntu-latest
      needs: [parrell]
      steps:
        - name: thrd jobs
          run: echo "3rd job"
        - name : third two
          run: "sthird two"